# default config start
%YAML 1.2
# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json
---
default_install_hook_types:
  - pre-commit
  - commit-msg
  - post-commit

default_stages:
  - commit

fail_fast: true

# Default config
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 #https://pre-commit.com/
    hooks:
      - id: check-xml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: check-merge-conflict
  # default config end
  # DevSecOps with GitGuardian Shield
  # Add your api key to your .env file or your .bashrc or .zshrc file | GITGUARDIAN_API_KEY=
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.28.0 # https://docs.gitguardian.com/ggshield-docs/integrations/git-hooks/pre-commit
    hooks:
      - id: ggshield
        language_version: python3
        stages: [commit]

  # Hadolint your Dockerfile
  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.12.1b3
    hooks:
      - id: hadolint
        args: [--ignore, DL3025, --ignore, DL3018]

    # Ruff linter and formatter for Python - https://github.com/astral-sh/ruff-pre-commit
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.11.10
      hooks:
          # Run the linter.
          - id: ruff-check
            types_or: [python, pyi]
            args: [--fix]
          # Run the formatter.
          - id: ruff-format
            types_or: [python, pyi]

  # Jira
  # Jira smart commits start
  - repo: https://github.com/radix-ai/auto-smart-commit
    rev: v1.0.3 # https://github.com/radix-ai/auto-smart-commit | pre-commit install --hook-type prepare-commit-msg
    hooks:
      - id: auto-smart-commit
  # Jira smart commits end

  # IaC
  # Terraform start
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0 # https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_checkov
      - id: terraform_docs
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_tfsec
      - id: terraform_validate
      - id: terrascan
      - id: tfupdate
      - id: infracost_breakdown
        args:
          - --args=--path=./
          - --args=--format=html
          - --args=--out-file infracost_report.html
          - --hook-config='.totalHourlyCost|tonumber > 0.1'
          - --hook-config='.totalHourlyCost|tonumber > 1'
          - --hook-config='.projects[].diff.totalMonthlyCost|tonumber != 10000'
          - --hook-config='.currency == "EUR"'
          - --hook-config=--path-to-file=TF-README.md # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
          - --hook-config=--add-to-existing-file=true # Boolean. true or false
          - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
        verbose: true # always show costs        args:
  # Terraform end

  # K8s Templating
  # Helm start
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.11.0 # https://github.com/norwoodj/helm-docs | You will need to configure a linter_values.yaml file
    hooks:
      - id: helm-docs
        args:
          # Chart search path
          - --chart-search-root=.
          # The `./` makes it relative to the chart-search-root set above
          - --template-files=./_templates.gotmpl
          # Repeating the flag adds this to the list, now [./_templates.gotmpl, README.md.gotmpl]
          # A base filename makes it relative to each chart directory found
          - --template-files=README.md.gotmpl
  # Helm end

  # Typo checker
  # Codespell start
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
  # Codespell end
  # Build tools
  # Maven start
  - repo: https://github.com/ejba/pre-commit-maven
    rev: v0.3.3
    hooks:
      - id: maven
        args: ["clean compile"]
      - id: maven-spotless-apply
    # -   id: ...
  # Maven end

  # Prettier code layout standard
  # https://prettier.io/
  # Prettier start
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.0.0-alpha.4
          - eslint-config-prettier
          - stylelint-config-prettier
          - prettier-plugin-java
          - prettier-plugin-sh
          - prettier-plugin-toml
          - "@prettier/plugin-xml"
  # Prettier end

  # MegaLinter by OX Security
  # MegaLinter start
  - repo: https://github.com/oxsecurity/megalinter
    rev: v6.8.0 # Git tag specifying the hook, not mega-linter-runner, version
    hooks:
      - id: megalinter-incremental # Faster, less thorough
        stages:
          - commit
      - id: megalinter-full # Slower, more thorough
        stages:
          - push
# MegaLinter end

# KubeConform Helm QA start
  - repo: https://github.com/jtyr/kubeconform-helm
    rev: v0.1.17
    hooks:
      - id: kubeconform-helm
        args:
          - --kubernetes-version=1.24.0
          - --verbose
          - --summary
# KubeConform Helm QA end

# Frigate Helm Chart create documentation start
  - repo: https://github.com/rapidsai/frigate/
    rev: v0.4.0 #  pre-commit autoupdate  - to keep the version up to date
    hooks:
      - id: frigate
        args:
          - --output=README.rst
          - --format=rst
          - --no-credits
          - --no-deps
# Frigate Helm Chart create documentation end
